### ISSUE TITLE
Activating the camera only when streamscreen opened

### ISSUE THREAD

**Issue by binflo13** [lucianolivares/Tutorial-Kivymd#12]
Thank you for your amazing work Luciano, this tutorial is being very helpful for me.

I would like to know if there is a way to only stream the camera images when the streamscreen is opened. If we are working with big images, everything slows down, so it would be very helpful to get this. Do you know how we could get this?

**Comment by lucianolivares** [comment]
Hi, first of all thank for the support. As I see it you just have to clean the camera box ( do the same as the deactivate camera button) with **ids.box_camera.clear_widgets()** when changing the screen.

**Comment by binflo13** [comment]
Thank you for your fast answer, Luciano. I would like also to run the update function from KivyStream in a separate thread. Does the Clock.schedule_interval execute the callback in a separate thread or do I have to do it on my own?

**Comment by lucianolivares** [comment]
Your welcome, 🤔 I think with threading library you can control better the threads.
